# Generated by Django 2.2.13 on 2020-10-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugin_prask_7_1_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlevel',
            name='level_id',
            field=models.IntegerField(),
        ),
    ]
