# Generated by Django 2.2.13 on 2020-10-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugin_prask_7_1_1', '0002_auto_20201003_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlevel',
            name='used_hint',
            field=models.BooleanField(default=False),
        ),
    ]
