# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-15 20:02
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("plugin_prask_1_2_1", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="usercategory",
            name="state",
            field=models.CharField(default="", max_length=256),
        )
    ]
