# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-17 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20170916_2349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventorganizer',
            options={'verbose_name': 'ved\xfaci akcie', 'verbose_name_plural': 'ved\xfaci akcie'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='semester',
        ),
    ]
