# Generated by Django 2.1.9 on 2019-10-06 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import trojsten.notifications.constants


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("message", models.TextField()),
                ("url", models.URLField(blank=True, null=True)),
                ("was_read", models.BooleanField(default=False)),
                ("was_email_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"verbose_name": "Notification", "verbose_name_plural": "Notifications"},
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (
                                trojsten.notifications.constants.SubscriptionStatus(0),
                                "Unsubscribed",
                            ),
                            (trojsten.notifications.constants.SubscriptionStatus(1), "Subscribed"),
                        ],
                        verbose_name="Status",
                    ),
                ),
                ("notification_type", models.PositiveIntegerField()),
                ("send_emails", models.BooleanField(default=True, verbose_name="Send emails?")),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.ContentType",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={"verbose_name": "Subscription", "verbose_name_plural": "Subscriptions"},
        ),
        migrations.AddField(
            model_name="notification",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="notifications.Subscription",
                verbose_name="Subscription",
            ),
        ),
    ]
