# Generated by Django 2.1.9 on 2019-10-06 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("notifications", "0003_auto_20191005_1634")]

    operations = [migrations.RemoveField(model_name="notification", name="user")]
