# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description_points',
            field=models.IntegerField(default=0, verbose_name='body za popis'),
        ),
        migrations.AlterField(
            model_name='task',
            name='has_description',
            field=models.BooleanField(default=False, verbose_name='odovz\xe1va sa popis'),
        ),
        migrations.AlterField(
            model_name='task',
            name='has_source',
            field=models.BooleanField(default=False, verbose_name='odovz\xe1va sa zdroj\xe1k'),
        ),
        migrations.AlterField(
            model_name='task',
            name='source_points',
            field=models.IntegerField(default=0, verbose_name='body za program'),
        ),
    ]
