# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20160502_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='has_description',
            field=models.BooleanField(default=False, verbose_name='odovzd\xe1va sa popis'),
        ),
        migrations.AlterField(
            model_name='task',
            name='has_source',
            field=models.BooleanField(default=False, verbose_name='odovzd\xe1va sa zdroj\xe1k'),
        ),
    ]
