# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 08:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20160606_1016'),
    ]

    database_operations = [
        migrations.AlterModelTable('Submit', 'submit_submit')
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
        )
    ]
