# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20160608_1051'),
    ]

    database_operations = [
        migrations.AlterModelTable('Task', 'contests_task'),
        migrations.AlterModelTable('Category', 'contests_category'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
        )
    ]
