# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20160608_1143'),
        ('results', '0003_auto_20160608_1143'),
        ('submit', '0002_auto_20160608_1143'),
        ('contests', '0003_category_task'),
    ]

    state_operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=state_operations)
    ]
