# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-07 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('results', '0002_auto_20160607_1400'),
        ('people', '0004_auto_20160502_1646'),
    ]

    database_operations = [
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.ForeignKey(default=1, help_text='Do pol\xed\u010dka nap\xed\u0161te skratku, \u010das\u0165 n\xe1zvu alebo adresy \u0161koly a n\xe1sledne vyberte spr\xe1vnu mo\u017enos\u0165 zo zoznamu. Pokia\u013e va\u0161a \u0161kola nie je v&nbsp;zozname, vyberte "Gymn\xe1zium in\xe9" a&nbsp;po\u0161lite n\xe1m e-mail.', null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.School', verbose_name='\u0161kola'),
        ),
        migrations.AlterModelTable('School', 'schools_school')
    ]

    state_operations = [
        migrations.DeleteModel(
            name='School',
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
