# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-07 12:00
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("people", "0004_auto_20160502_1646")]

    database_operations = [migrations.AlterModelTable("School", "schools_school")]

    operations = [migrations.SeparateDatabaseAndState(database_operations=database_operations)]
