# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-07 12:00
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("results", "0001_squashed_0003_auto_20160608_1143"),
        ("people", "0006_auto_20160607_1400"),
    ]

    state_operations = [migrations.DeleteModel(name="School")]

    operations = [migrations.SeparateDatabaseAndState(state_operations=state_operations)]
