# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-26 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_userpropertykey_regex'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mail_to_school',
            field=models.BooleanField(default=False, verbose_name='posielanie do \u0161koly'),
        ),
    ]
