# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-04 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("people", "0009_user_mail_to_school"), ("people", "0009_auto_20160920_0926")]

    operations = []
