# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-26 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_user_mail_to_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mail_to_school',
        ),
        migrations.AddField(
            model_name='user',
            name='mailing_option',
            field=models.CharField(choices=[('HOME', 'domov'), ('SCHOOL', 'do skoly'), ('OTHER', 'inde')], default='HOME', max_length=6, verbose_name='adresa kore\u0161pondencie'),
        ),
    ]
