# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-25 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_user_mail_to_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpropertykey',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='skryt\xe9'),
        ),
    ]
