# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-22 18:10
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("people", "0010_merge")]

    operations = [
        migrations.AddField(
            model_name="userpropertykey",
            name="hidden",
            field=models.BooleanField(default=False, verbose_name="skryt\xe9"),
        )
    ]
