# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-31 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_auto_20160826_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=70, verbose_name='ulica')),
                ('town', models.CharField(db_index=True, max_length=64, verbose_name='mesto')),
                ('postal_code', models.CharField(db_index=True, max_length=16, verbose_name='PS\u010c')),
                ('addr_name', models.CharField(blank=True, max_length=100, verbose_name='n\xe1zov v adrese')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Adresa',
                'verbose_name_plural': 'Adresy',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='mailing_option',
            field=models.CharField(choices=[('HOME', 'domov'), ('SCHOOL', 'do \u0161koly'), ('OTHER', 'na in\xfa adresu (napr. na intern\xe1t)')], default='HOME', max_length=6, verbose_name='adresa kore\u0161pondencie'),
        ),
    ]
