# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-02 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_auto_20170302_2034'),
        ('people', '0011_userpropertykey_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ignored_competitions',
            field=models.ManyToManyField(to='contests.Competition', verbose_name='ignorovan\xe9 s\xfa\u0165a\u017ee'),
        ),
    ]
