# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-18 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_userpropertykey_hidden'),
        ('people', '0012_auto_20170103_1947'),
    ]

    operations = [
    ]
