# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-21 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0012_auto_20170103_1947'),
        ('people', '0015_auto_20170916_1917'),
    ]

    operations = [
    ]
