# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-19 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0016_merge_20180121_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
    ]
