# Generated by Django 2.1.9 on 2019-07-04 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("people", "0017_auto_20180615_1508"), ("people", "0017_auto_20180915_2002")]

    operations = []
