# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-07 09:58
from __future__ import unicode_literals
from datetime import date

from django.db import migrations


def migrate_schools(apps, schema_editor):
    User = apps.get_model('people', 'User')
    UserSchool = apps.get_model('people', 'UserSchool')
    for user in User.objects.all():
        if user.school:
            UserSchool.objects.create(
                user=user,
                school=user.school,
                start_time=date(max(user.graduation - 8, 1) if user.graduation else 1, 9, 1)
            )


def reverse_migrate_schools(apps, schema_editor):
    UserSchool = apps.get_model('people', 'UserSchool')
    for row in UserSchool.objects.order_by('user', '-start_time').distinct('user'):
        row.user.school = row.school
        row.user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0017_auto_20180607_1156'),
    ]

    operations = [
        migrations.RunPython(migrate_schools, reverse_migrate_schools)
    ]
