# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-08 19:24
from __future__ import unicode_literals

import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0018_auto_20180607_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='school',
        ),
        migrations.AlterField(
            model_name='userschool',
            name='start_time',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Start of study'),
        ),
    ]
