# Generated by Django 2.1.9 on 2019-07-07 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("people", "0018_auto_20190704_2042"), ("people", "0019_auto_20190704_1807")]

    operations = []
