# Generated by Django 2.1.9 on 2019-10-05 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0020_merge_20190707_1047'),
        ('people', '0018_auto_20190925_1918'),
    ]

    operations = [
    ]
