# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-16 20:24
from django.db import migrations


def replace_default_school_with_null(apps, schema_editor):
    try:
        default_school = (
            apps.get_model("schools", "School").objects.filter(verbose_name="Iná škola").get()
        )
    except apps.get_model("schools", "School").DoesNotExist:
        return

    users = apps.get_model("people", "User")
    for user in users.objects.filter(school=default_school):
        user.school = None
        user.save()
    results = apps.get_model("results", "FrozenUserResult")
    for result in results.objects.filter(school=default_school):
        result.school = None
        result.save()
    default_school.delete()


def revert_replace_default_school_with_null(apps, schema_editor):
    School = apps.get_model("schools", "School")
    default_school = School(
        pk=1,
        abbreviation="",
        verbose_name="Iná škola",
        addr_name="",
        street="",
        city="",
        zip_code="",
    )
    default_school.save()
    User = apps.get_model("people", "User")
    for user in User.objects.filter(school=None):
        user.school = default_school
        user.save()
    FrozenUserResult = apps.get_model("results", "FrozenUserResult")
    for result in FrozenUserResult.objects.filter(school=None):
        result.school = default_school
        result.save()


class Migration(migrations.Migration):
    dependencies = [("schools", "0001_initial")]

    operations = [
        migrations.RunPython(
            replace_default_school_with_null, revert_replace_default_school_with_null
        )
    ]
