# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-19 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiplomaTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('svg', models.CharField(max_length=5000000)),
            ],
        ),
    ]
