# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-16 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiplomaDataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Source name')),
                ('class_name', models.CharField(choices=[('file_upload', 'file_upload'), ('naboj_physics', 'naboj_physics'), ('naboj_math', 'naboj_math')], max_length=128, verbose_name='Implemented source class')),
                ('is_default', models.BooleanField(default=False, verbose_name='Add to predefined sources')),
            ],
            options={
                'verbose_name': 'Zdroj dát pre diplomy',
                'verbose_name_plural': 'Zdroje dát pre diplomy',
            },
        ),
        migrations.CreateModel(
            name='DiplomaTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('svg', models.TextField()),
                ('sources', models.ManyToManyField(blank=True, to='diplomas.DiplomaDataSource')),
            ],
            options={
                'verbose_name': 'Šablóna diplomu',
                'verbose_name_plural': 'Šablóny diplomov',
            },
        ),
    ]
