# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-19 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diplomas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diplomatemplate',
            options={'verbose_name': 'Šablóna diplomu', 'verbose_name_plural': 'Šablóny diplomov'},
        ),
    ]
