# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-19 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomas', '0002_auto_20180619_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diplomatemplate',
            name='svg',
            field=models.TextField(),
        ),
    ]
