# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-16 16:13
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("contests", "0003_round_second_end_time")]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="required_user_props",
            field=models.ManyToManyField(
                blank=True,
                to="people.UserPropertyKey",
                verbose_name="Povinn\xe9 vlastnosti \u010dloveka",
            ),
        )
    ]
