# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-10 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_auto_20160910_1302'),
    ]

    operations = [
        migrations.RenameModel('Series', 'Semester'),
        migrations.RenameField('Round', 'series', 'semester'),
    ]
