# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-17 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20170917_1333'),
        ('contests', '0004_auto_20170716_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='camp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Event', verbose_name='s\xfastredenie'),
        ),
    ]
