# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-23 15:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contests', '0006_auto_20160925_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskPeople',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.IntegerField(choices=[(0, 'opravovate\u013e'), (1, 'vzor\xe1kova\u010d'), (2, 'recenzova\u010d')], verbose_name='funkcia')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ved\xfaci')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Task', verbose_name='task')),
            ],
            options={
                'verbose_name': 'Predelen\xe1 osoba',
                'verbose_name_plural': 'Pridelen\xed \u013eudia',
            },
        ),
    ]
