# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-07 19:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from trojsten.contests.models import Task, TaskPeople
from trojsten.contests import constants


def fill_task_people(apps, schema_editor):
    for task in Task.objects.all():
        if task.reviewer:
            TaskPeople.objects.create(
                task=task,
                person=task.reviewer,
                function=constants.TASK_FUNCTION_REVIEWER
            )


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contests', '0006_auto_20160925_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskPeople',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.IntegerField(choices=[(0, 'reviewer'), (1, 'solution-writer'), (2, 'proofreader')], verbose_name='function')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='organizer')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Task', verbose_name='task')),
            ],
            options={
                'verbose_name': 'Assigned person',
                'verbose_name_plural': 'Assigned people',
            },
        ),
        migrations.RunPython(fill_task_people, reverse),
    ]
