# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-23 15:08
from __future__ import unicode_literals

from django.db import migrations

from trojsten.contests import constants


def fill_task_people(apps, schema_editor):
    Task = apps.get_model('contests', 'Task')
    TaskPeople = apps.get_model('contests', 'TaskPeople')
    for task in Task.objects.all():
        if task.reviewer:
            TaskPeople.objects.create(
                task=task,
                person=task.reviewer,
                function=constants.TASK_FUNCTION_REVIEWER
            )


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0007_taskpeople'),
    ]

    operations = [
        migrations.RunPython(fill_task_people, reverse)
    ]
