# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-23 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0008_auto_20161023_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='reviewer',
        ),
    ]
