# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-21 16:16
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0008_auto_20170228_2341"),
        ("contests", "0004_auto_20170716_1813"),
    ]

    operations = []
