# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-13 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0010_round_results_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='founded',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year of foundation'),
        ),
    ]
