# Generated by Django 2.1.9 on 2019-10-05 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contests", "0017_auto_20190707_1059"),
        ("contests", "0016_auto_20190925_1918"),
    ]

    operations = []
