# Generated by Django 2.2.13 on 2020-09-13 16:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contests", "0019_auto_20191212_1830"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="susi_big_hint",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True, max_length=128, null=True, verbose_name="veľký hint"
                ),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="susi_small_hint",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True, max_length=128, null=True, verbose_name="malý hint"
                ),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="text_submit_solution",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    max_length=512,
                    null=True,
                    verbose_name="správne riešenie pri odovzdávaní textu",
                ),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
    ]
