# Generated by Django 2.2.13 on 2020-09-07 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0020_auto_20200907_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='susi_second_hint',
            new_name='susi_big_hint',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='susi_first_hint',
            new_name='susi_small_hint',
        ),
    ]
