# Generated by Django 2.2.13 on 2020-09-13 16:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contests", "0021_auto_20200907_2100"),
    ]

    operations = [
        migrations.RemoveField(model_name="task", name="has_text_submit",),
        migrations.AlterField(
            model_name="task",
            name="text_submit_solution",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    max_length=512,
                    null=True,
                    verbose_name="správne riešenie pri odovzdávaní textu",
                ),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
    ]
