# Generated by Django 2.2.24 on 2022-09-15 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0021_susi_issue_1403"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="taskpeople",
            options={"verbose_name": "Assigned user", "verbose_name_plural": "Assigned people"},
        ),
        migrations.AlterField(
            model_name="task",
            name="description_points_visible",
            field=models.BooleanField(default=False, verbose_name="Show description points"),
        ),
        migrations.AlterField(
            model_name="task",
            name="email_on_code_submit",
            field=models.BooleanField(
                default=False, verbose_name="Send notification to reviewers about new code submit"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="email_on_desc_submit",
            field=models.BooleanField(
                default=False,
                verbose_name="Send notification to reviewers about new description submit",
            ),
        ),
        migrations.AlterField(
            model_name="taskpeople",
            name="role",
            field=models.IntegerField(
                choices=[(0, "reviewer"), (1, "solution writer"), (2, "proofreader")],
                verbose_name="role",
            ),
        ),
        migrations.AlterField(
            model_name="taskpeople",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_people",
                to="contests.Task",
                verbose_name="task",
            ),
        ),
        migrations.AlterField(
            model_name="taskpeople",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="organizer",
            ),
        ),
    ]
