# Generated by Django 2.2.24 on 2022-09-15 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contests", "0022_auto_20220915_1320"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="taskpeople",
            options={"verbose_name": "Pridelený človek", "verbose_name_plural": "Pridelení ľudia"},
        ),
        migrations.AlterField(
            model_name="task",
            name="description_points_visible",
            field=models.BooleanField(
                default=False, verbose_name="Zobrazovať body za popis vo výsledkovke"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="email_on_code_submit",
            field=models.BooleanField(
                default=False, verbose_name="Zaslať opravovateľom notifikáciu o submite kódu"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="email_on_desc_submit",
            field=models.BooleanField(
                default=False, verbose_name="Zaslať opravovateľom notifikáciu o submite popisu"
            ),
        ),
        migrations.AlterField(
            model_name="taskpeople",
            name="role",
            field=models.IntegerField(
                choices=[(0, "opravovateľ"), (1, "vzorákovač"), (2, "recenzovač")],
                verbose_name="funkcia",
            ),
        ),
        migrations.AlterField(
            model_name="taskpeople",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_people",
                to="contests.Task",
                verbose_name="úloha",
            ),
        ),
        migrations.AlterField(
            model_name="taskpeople",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="vedúci",
            ),
        ),
    ]
