# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-10 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugin_ksp_32_3_1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='levelsolved',
            old_name='series',
            new_name='semester',
        ),
        migrations.AlterUniqueTogether(
            name='levelsolved',
            unique_together=set([('user', 'semester', 'level')]),
        ),
    ]
