# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-21 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugin_ksp_32_3_1', '0002_auto_20160910_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='levelsolved',
            old_name='semester',
            new_name='series',
        ),
        migrations.AlterUniqueTogether(
            name='levelsolved',
            unique_together=set([('user', 'series', 'level')]),
        ),
    ]
