# Generated by Django 2.1.14 on 2019-12-29 17:17

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='text2',
            field=models.CharField(default='a', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='text2',
            field=models.CharField(default='a', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='text2',
            field=models.CharField(default='a', max_length=1000),
            preserve_default=False,
        ),
    ]
