# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 09:43
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("old_submit", "0001_initial"), ("contests", "0003_category_task")]

    operations = [
        migrations.AlterField(
            model_name="submit",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contests.Task",
                verbose_name="\xfaloha",
            ),
        )
    ]
