# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-03 18:39
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("old_submit", "0004_auto_20170108_1728")]

    operations = [
        migrations.AlterField(
            model_name="submit",
            name="tester_response",
            field=models.CharField(
                blank=True,
                help_text=(
                    "O\u010dak\xe1van\xe9 odpovede s\xfa CERR, TLE, WA, MLE, OK, IGN, SEC, EXC"
                ),
                max_length=10,
                verbose_name="odpove\u010f testova\u010da",
            ),
        )
    ]
