# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-14 11:01
from __future__ import unicode_literals

import logging
from django.conf import settings
from django.db import migrations

from trojsten.submit import constants
from trojsten.submit.models import Submit


def migrate_protocols(*args, **kwargs):
    submits = Submit.objects.filter(protocol__isnull=True, submit_type=constants.SUBMIT_TYPE_SOURCE)
    logging.info('Unprocessed submit object count: {}'.format(submits.count()))

    for submit in submits:
        try:
            protocol_path = submit.filepath.rsplit('.', 1)[0] + settings.PROTOCOL_FILE_EXTENSION
            with open(protocol_path) as protocol_file:
                submit.protocol = protocol_file.read()
                submit.save()
        except IOError as e:
            logging.warning(e)


class Migration(migrations.Migration):
    dependencies = [
        ('old_submit', '0005_auto_20180915_2002'),
    ]

    operations = [
        migrations.RunPython(migrate_protocols)
    ]
