# -*- coding: utf-8 -*-
# Common constants for people

GRADUATION_SCHOOL_YEAR = 4
SCHOOL_YEAR_END_MONTH = 8
GRADUATION_YEAR_MIN = 1957
GRADUATION_YEAR_MAX_AHEAD = 10

USER_PROP_PREFIX = "user_prop_"
COMPETITION_PREFIX = "competition_"

MAILING_OPTION_HOME = "H"
MAILING_OPTION_SCHOOL = "S"
MAILING_OPTION_OTHER = "O"

DEENVELOPING_NOT_REVIEWED_SYMBOL = "*"
