# Generated by Django 2.2.24 on 2022-09-15 13:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0022_auto_20220915_1320"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0001_squashed_0007_auto_20170917_2343"),
        ("rules", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FKSLevel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "new_level",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ]
                    ),
                ),
                (
                    "last_semester_before_level_up",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="FKS_next_semester_level_ups",
                        to="contests.Semester",
                    ),
                ),
                (
                    "source_camp",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.Event",
                    ),
                ),
                (
                    "source_semester",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="FKS_caused_level_ups",
                        to="contests.Semester",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
